apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tc-s1-32
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: github-registry
      restartPolicy: Always
      containers:
        - name: backend
          image: ghcr.io/flavioneubauer/tc-s1-32:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.tc-s1-32:5432/tc
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: "DB_USERNAME"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: "DB_PASSWORD"
          readinessProbe:
            initialDelaySeconds: 20
            successThreshold: 1
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            initialDelaySeconds: 20
            failureThreshold: 3
            successThreshold: 1
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "250Mi"
            limits:
              cpu: "2"
              memory: "1024Mi"