version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: tc
      POSTGRES_PASSWORD: postgres
  app:
    container_name: application
    image: tc-s1-32:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports: 
        - 8080:8080
    depends_on:
        - db
    environment:
        spring.datasource.url: jdbc:postgresql://db:5432/tc
    pull_policy: always
    restart: on-failure
