apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
  namespace: tc-s1-32
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/tc-s1-32"
    type: DirectoryOrCreate