apiVersion: v1
kind: Service
metadata:
  name: tc-s1-32-nlb
  namespace: tc-s1-32
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
