
on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '17'
            - name: Build project
              run: ./mvnw install -DskipTests && ./mvnw spring-boot:run -pl application
            - name: Login Docker Hub
              run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            - name: Build docker image
              run: docker build -t davimassarumuta/aplicationOnFiap .
            - name: Push image docker
              run: docker push davimassarumuta/aplicationOnFiap
              
    deployEc2:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull image from docker hub
              run: docker pull davimassarumuta/aplicationOnFiap:latest
            - name: Remove docker container
              run: docker rm -f aplicationOnFiap
            - name: Run docker container
              run: docker run -d -p 8080:8080 8081:8081 8082:8082 8083:8083 8084:8084 8085:8085  -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' -e DATABASE_URL=${{secrets.DATABASE_URL}} --name aplicationOnFiap davimassarumuta/aplicationOnFiap
